name: Build app and upload artifacts 

on:
  push:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: react-tauri

jobs:
  build_and_upload:
    strategy:
      fail-fast: false
      matrix: 
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps: 
      - uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: setup rust
        run: rustup toolchain install stable --profile minimal
        
      - name: setup rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri -> target
          
      - name: install system dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: install app dependencies
        run: npm install
        
      - name: build app
        run: npm run tauri build
        
      - name: Archive production installers
        uses: actions/upload-artifact@v3
        with: 
          name: ${{ matrix.platform }} Installers 
          path: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/msi/*.msi
     
      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }} binaries
          path: |
            src-tauri/target/release/${{env.APP_NAME}}
            src-tauri/target/release/${{env.APP_NAME}}.exe
